openapi: 3.0.3
info:
  title: FarmStall API
  version: v1
servers:
- url: https://farmstall.designapis.com/v1  
paths: 
  /reviews:
    post:
      description: Create a new review
      requestBody:
        description: A new Review
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                userId:
                  type: string
                  pattern: '^[0-9a-fA-F\-]{36}$'
                  nullable: true
      responses:
        '201':
          description: Successfully created a new Review
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rating:
                      type: integer
                      minimum: 1
                      maximum: 5
                      example: 1
                    message:
                      type: string
                      example: An awesome time for the whole family.
                    uuid:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                    userId:
                      type: string
                      pattern: '^[0-9a-fA-F\-]{36}$'
                      nullable: true  